const ACTION_TYPES = {
  GET_CARDS_ACTION: "GET_CARDS_ACTION",
  GET_CARDS_REQUEST: "GET_CARDS_REQUEST",
  GET_CARDS_SUCCESS: "GET_CARDS_SUCCESS",
  GET_CARDS_ERROR: "GET_CARDS_ERROR",
};
export default ACTION_TYPES;
